# Visit http://dev.bukkit.org/server-mods/signtimer/ for more info.
settings:
  broadcast_times: false
  include_days: false
  include_milli: true
  compact_time: true

messages:
  broadcast_message: "%PLAYERNAME% finished in %TIME%"
  player_message: "Your time was %TIME%"

DB:
  driver: 'org.sqlite.JDBC'
  url: 'jdbc:sqlite:{DIR}{NAME}.db'
  username: 'root'
  password: ''
  isolation: 'SERIALIZABLE'
  logging: false
  rebuild: false