name: SignTimer
version: 1.1.0
description: A countdown timer using signs.
authors: [Muddr]
main: com.gtdclan.signtimer.Main

commands:
  st:
    description: Main command for SignTimer.
    usage: Error! Type /<command> for help.
permissions:
  signtimer.removesigns:
    description: Allows player to remove timer signs.
    default: op
  signtimer.createsigns:
    description: Allows player to create timer signs.
    default: op
  signtimer.cleartimes:
    description: Allows player to clear all times.
    default: op