name: SignTimer
version: 2.0.0
description: A countdown timer using signs.
authors: [Muddr]
main: com.gtdclan.signtimer.Main

commands:
  st:
    description: Main command for SignTimer.
    usage: Error! Type /<command> for help.
permissions:
  signtimer.removesigns:
    description: Allows player to remove timer signs.
    default: op
  signtimer.createsigns:
    description: Allows player to create timer signs.
    default: op
  signtimer.cleartimes:
    description: Allows player to clear all times for a timer.
    default: op
  signtimer.enabledisable:
    description: Allows player to enable/disable timers.
    default: op
  signtimer.rename:
    description: Allows player to rename timers.
    default: op  
  signtimer.delete:
    description: Allows player to delete timers.
    default: op  
  signtimer.list:
    description: Allows player to list timers.
    default: op  